# Generated by Django 5.1.2 on 2024-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('isbn', models.CharField(max_length=20)),
                ('isbn13', models.CharField(max_length=20)),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.PositiveIntegerField()),
                ('ratings_count', models.PositiveIntegerField()),
                ('text_reviews_count', models.PositiveIntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
    ]
