# Generated by Django 5.1.2 on 2024-10-25 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='outstanding',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
