# Generated by Django 5.1.2 on 2024-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_outstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
