# Generated by Django 5.1.2 on 2024-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_book_id_book_bookid_transaction_issued_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_late',
        ),
        migrations.AddField(
            model_name='transaction',
            name='issue_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
