# Generated by Django 5.1.2 on 2024-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_transaction_is_late_transaction_issue_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='return_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_complete',
            field=models.BooleanField(default=False),
        ),
    ]
