# Generated by Django 5.1.2 on 2024-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_transaction_issue_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='return_complete',
        ),
        migrations.AddField(
            model_name='book',
            name='qty_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
