# Generated by Django 5.1.2 on 2024-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_transaction_return_complete_book_qty_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='penalty_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
