# Generated by Django 5.1.2 on 2024-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_member_outstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='qty_in_stock',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
